// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// HorsesColumns holds the columns for the "horses" table.
	HorsesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "user_horses", Type: field.TypeInt, Nullable: true},
	}
	// HorsesTable holds the schema information for the "horses" table.
	HorsesTable = &schema.Table{
		Name:       "horses",
		Columns:    HorsesColumns,
		PrimaryKey: []*schema.Column{HorsesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "horses_users_horses",
				Columns:    []*schema.Column{HorsesColumns[2]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "username", Type: field.TypeString},
		{Name: "password", Type: field.TypeString},
		{Name: "email", Type: field.TypeString},
		{Name: "verified", Type: field.TypeBool, Default: false},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		HorsesTable,
		UsersTable,
	}
)

func init() {
	HorsesTable.ForeignKeys[0].RefTable = UsersTable
}
