// Code generated by ent, DO NOT EDIT.

package ent

import (
	"api/ent/horse"
	"api/ent/user"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// HorseCreate is the builder for creating a Horse entity.
type HorseCreate struct {
	config
	mutation *HorseMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (hc *HorseCreate) SetName(s string) *HorseCreate {
	hc.mutation.SetName(s)
	return hc
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (hc *HorseCreate) SetOwnerID(id int) *HorseCreate {
	hc.mutation.SetOwnerID(id)
	return hc
}

// SetNillableOwnerID sets the "owner" edge to the User entity by ID if the given value is not nil.
func (hc *HorseCreate) SetNillableOwnerID(id *int) *HorseCreate {
	if id != nil {
		hc = hc.SetOwnerID(*id)
	}
	return hc
}

// SetOwner sets the "owner" edge to the User entity.
func (hc *HorseCreate) SetOwner(u *User) *HorseCreate {
	return hc.SetOwnerID(u.ID)
}

// Mutation returns the HorseMutation object of the builder.
func (hc *HorseCreate) Mutation() *HorseMutation {
	return hc.mutation
}

// Save creates the Horse in the database.
func (hc *HorseCreate) Save(ctx context.Context) (*Horse, error) {
	return withHooks(ctx, hc.sqlSave, hc.mutation, hc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (hc *HorseCreate) SaveX(ctx context.Context) *Horse {
	v, err := hc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (hc *HorseCreate) Exec(ctx context.Context) error {
	_, err := hc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (hc *HorseCreate) ExecX(ctx context.Context) {
	if err := hc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (hc *HorseCreate) check() error {
	if _, ok := hc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Horse.name"`)}
	}
	return nil
}

func (hc *HorseCreate) sqlSave(ctx context.Context) (*Horse, error) {
	if err := hc.check(); err != nil {
		return nil, err
	}
	_node, _spec := hc.createSpec()
	if err := sqlgraph.CreateNode(ctx, hc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	hc.mutation.id = &_node.ID
	hc.mutation.done = true
	return _node, nil
}

func (hc *HorseCreate) createSpec() (*Horse, *sqlgraph.CreateSpec) {
	var (
		_node = &Horse{config: hc.config}
		_spec = sqlgraph.NewCreateSpec(horse.Table, sqlgraph.NewFieldSpec(horse.FieldID, field.TypeInt))
	)
	if value, ok := hc.mutation.Name(); ok {
		_spec.SetField(horse.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if nodes := hc.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   horse.OwnerTable,
			Columns: []string{horse.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_horses = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// HorseCreateBulk is the builder for creating many Horse entities in bulk.
type HorseCreateBulk struct {
	config
	err      error
	builders []*HorseCreate
}

// Save creates the Horse entities in the database.
func (hcb *HorseCreateBulk) Save(ctx context.Context) ([]*Horse, error) {
	if hcb.err != nil {
		return nil, hcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(hcb.builders))
	nodes := make([]*Horse, len(hcb.builders))
	mutators := make([]Mutator, len(hcb.builders))
	for i := range hcb.builders {
		func(i int, root context.Context) {
			builder := hcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*HorseMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, hcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, hcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, hcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (hcb *HorseCreateBulk) SaveX(ctx context.Context) []*Horse {
	v, err := hcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (hcb *HorseCreateBulk) Exec(ctx context.Context) error {
	_, err := hcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (hcb *HorseCreateBulk) ExecX(ctx context.Context) {
	if err := hcb.Exec(ctx); err != nil {
		panic(err)
	}
}
