// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Horse is the predicate function for horse builders.
type Horse func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
